name: PR Build Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  contents: read

jobs:
  pr_check:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            pnpm install --frozen-lockfile
          else
            pnpm install
          fi

      - name: Set Test Environment Variables
        run: |
          echo "NEXT_PUBLIC_LANGGRAPH_ASSISTANT_ID=test-assistant-id" >> $GITHUB_ENV
          echo "LANGCHAIN_API_KEY=test-api-key" >> $GITHUB_ENV
          echo "LANGGRAPH_API_URL=http://test-url" >> $GITHUB_ENV
          echo "AUTH0_SECRET=test-secret" >> $GITHUB_ENV
          echo "AUTH0_BASE_URL=http://localhost:3000" >> $GITHUB_ENV
          echo "AUTH0_ISSUER_BASE_URL=https://test.auth0.com" >> $GITHUB_ENV
          echo "AUTH0_CLIENT_ID=test-client-id" >> $GITHUB_ENV
          echo "AUTH0_CLIENT_SECRET=test-client-secret" >> $GITHUB_ENV
          echo "AUTH0_AUDIENCE=test-audience" >> $GITHUB_ENV
          echo "AUTH0_SCOPE=openid profile email" >> $GITHUB_ENV

      - name: Build
        run: pnpm build

      - name: Run Tests
        run: pnpm test
