name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set PR Environment Variables
        run: |
          echo "PR_ENV_NAME=teachers-eddo-ai-pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "DEPLOY_URL=https://${PR_ENV_NAME}.azurecontainerapps.io" >> $GITHUB_ENV
          echo "AUTH0_BASE_URL=https://${PR_ENV_NAME}.azurecontainerapps.io" >> $GITHUB_ENV  # Set AUTH0_BASE_URL
          echo "AUTH0_SCOPE='openid profile email email_verified'" >> $GITHUB_ENV # Set AUTH0_SCOPE

      - name: Set Variables from Workflow Environment Context
        run: |
          echo "NEXT_PUBLIC_LANGGRAPH_ASSISTANT_ID=${{ vars.NEXT_PUBLIC_LANGGRAPH_ASSISTANT_ID }}" >> $GITHUB_ENV

      - name: Set Secrets from Workflow Environment Context
        run: |
          echo "LANGCHAIN_API_KEY=${{ secrets.LANGCHAIN_API_KEY }}" >> $GITHUB_ENV
          echo "LANGGRAPH_API_URL=${{ secrets.LANGGRAPH_API_URL }}" >> $GITHUB_ENV
          echo "AUTH0_SECRET=${{ secrets.AUTH0_SECRET }}" >> $GITHUB_ENV
          echo "AUTH0_ISSUER_BASE_URL=${{ secrets.AUTH0_ISSUER_BASE_URL }}" >> $GITHUB_ENV
          echo "AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}" >> $GITHUB_ENV
          echo "AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}" >> $GITHUB_ENV
          echo "AUTH0_SCOPE=${{ secrets.AUTH0_SCOPE }}" >> $GITHUB_ENV

      - name: Copy Configuration File Based on Environment
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            cp staticwebapp.config.production.json staticwebapp.config.json
          else
            cp staticwebapp.config.staging.json staticwebapp.config.json
          fi

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_COAST_0AE46E91E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env:
          PR_ENV_NAME: ${{ env.PR_ENV_NAME }}
          DEPLOY_URL: ${{ env.DEPLOY_URL }}
          AUTH0_BASE_URL: ${{ env.AUTH0_BASE_URL }}
          AUTH0_SCOPE: ${{ env.AUTH0_SCOPE }}
          NEXT_PUBLIC_LANGGRAPH_ASSISTANT_ID: ${{ env.NEXT_PUBLIC_LANGGRAPH_ASSISTANT_ID }}
          LANGCHAIN_API_KEY: ${{ env.LANGCHAIN_API_KEY }}
          LANGSMITH_API_KEY: ${{ env.LANGCHAIN_API_KEY }}
          LANGGRAPH_API_URL: ${{ env.LANGGRAPH_API_URL }}
          AUTH0_SECRET: ${{ env.AUTH0_SECRET }}
          AUTH0_ISSUER_BASE_URL: ${{ env.AUTH0_ISSUER_BASE_URL }}
          AUTH0_CLIENT_ID: ${{ env.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ env.AUTH0_CLIENT_SECRET }}
          AUTH0_AUDIENCE: ${{ env.AUTH0_AUDIENCE }}

      - name: Test Password Protection in Staging
        if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/main' }}
        run: |
          curl -I https://${{ env.DEPLOY_URL }} | grep "401 Unauthorized"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_COAST_0AE46E91E }}
          action: "close"
